// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://athviqqfowpafvpgarua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0aHZpcXFmb3dwYWZ2cGdhcnVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTg4MzEsImV4cCI6MjA2NDQ3NDgzMX0.JpEeZiIbgO47WptDs8zGM7pzVQhAF0nSuRbqGDUBiKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);